# Generated by Django 5.1.6 on 2025-04-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task comment', 'verbose_name_plural': 'Task comments'},
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='taskcomment',
            table='task_comment',
        ),
    ]
