# Generated by Django 5.1.6 on 2025-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='gender',
            field=models.CharField(choices=[('hr', 'Male'), ('female', 'Female'), ('other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='user_role',
            field=models.CharField(choices=[('hr', 'HR'), ('leader', 'Leader'), ('employee', 'Employee')], verbose_name='Role in Company'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('hr', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
