"""
Django settings for team_tracker project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from team_tracker.config import (django_app, drf, spectacular)
from team_tracker import env
import os

# settings come from team_tracker import env
BASE_DIR = env.BASE_DIR
SECRET_KEY = env.SECRET_KEY
DEBUG = env.DEBUG
ALLOWED_HOSTS = env.ALLOWED_HOSTS

# settings come from config import django_app
INSTALLED_APPS = django_app.DJANGO_DEFAULT_APPS + django_app.LOCAL_APPS + django_app.THIRD_PARTY_APPS
MIDDLEWARE = django_app.MIDDLEWARE
AUTH_PASSWORD_VALIDATORS = django_app.AUTH_PASSWORD_VALIDATORS
TEMPLATES = django_app.TEMPLATES


# settings come from config import drf
REST_FRAMEWORK = drf.REST_FRAMEWORK

SPECTACULAR_SETTINGS = spectacular.SPECTACULAR_SETTINGS

ROOT_URLCONF = 'team_tracker.urls'

WSGI_APPLICATION = 'team_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.PMS_DB_NAME,
        'USER': env.PMS_DB_USER,
        'PASSWORD': env.PMS_DB_PASSWORD,
        'HOST': env.PMS_DB_HOST,
        'PORT': env.PMS_DB_PORT,
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(env.BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.TeamUser'

LOGIN_URL = '/user/login/'

LOGIN_REDIRECT_URL = '/user/profile/'